name: developSEEDS

on:
  pull_request:
    branches:
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies #install the dependecies
      run: npm install

    #- name: Run the tests #run the test script
     # run: npm test

    #- name: lint #run eslint to check code standard
     # run: npm run lint

    - name: Build # build the application
      run: npm run build
      
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "developseed" #Must be unique in Heroku
          heroku_email: "gerrit2209@gmail.com"

